# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [99]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [2]:
nparr

array([[145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156],
       [157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168],
       [169, 170, 171, 172, 173, 174],
       [175, 176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185, 186],
       [187, 188, 189, 190, 191, 192],
       [193, 194, 195, 196, 197, 198],
       [199, 200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209, 210],
       [211, 212, 213, 214, 215, 216]])

In [3]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)

In [4]:
# 1 Shape

nparr.shape

(12, 6)

In [5]:
# 1 Dimensions

nparr.ndim

2

In [6]:
# 1 Elements

nparr.dtype

dtype('int64')

In [7]:
# 2 Standard Deviation

round(np.std(nparr),2)

20.78

In [8]:
# 3 Position of Max Value

maxpos = np.argmax(nparr)
print(f"The maximum value in nparr is at position {maxpos}.")

The maximum value in nparr is at position 71.


In [9]:
# 4 Array of Zeros

array0 = np.zeros_like(nparr)
array0

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [10]:
# 5 Array of Ones

array1 = np.ones_like(nparr)
array1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [12]:
# 6 Square Root Array

array_sqrt = np.round(np.sqrt(nparr),2)
array_sqrt

array([[12.04, 12.08, 12.12, 12.17, 12.21, 12.25],
       [12.29, 12.33, 12.37, 12.41, 12.45, 12.49],
       [12.53, 12.57, 12.61, 12.65, 12.69, 12.73],
       [12.77, 12.81, 12.85, 12.88, 12.92, 12.96],
       [13.  , 13.04, 13.08, 13.11, 13.15, 13.19],
       [13.23, 13.27, 13.3 , 13.34, 13.38, 13.42],
       [13.45, 13.49, 13.53, 13.56, 13.6 , 13.64],
       [13.67, 13.71, 13.75, 13.78, 13.82, 13.86],
       [13.89, 13.93, 13.96, 14.  , 14.04, 14.07],
       [14.11, 14.14, 14.18, 14.21, 14.25, 14.28],
       [14.32, 14.35, 14.39, 14.42, 14.46, 14.49],
       [14.53, 14.56, 14.59, 14.63, 14.66, 14.7 ]])

In [41]:
# 7 Transpose Array

np.round(np.dot(array1,np.transpose(nparr)),2)

array([[ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  957,  993, 1029, 1065, 1101, 1137, 1173, 1209, 1245,
        1281],
       [ 885,  921,  

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [14]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)

In [15]:
# Load Data Frame

a_df

iata                            airport               city state country  \
0    ORD       Chicago O'Hare International            Chicago    IL     USA   
1    ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2    DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3    PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4    DEN                        Denver Intl             Denver    CO     USA   
..   ...                                ...                ...   ...     ...   
216  EAU           Chippewa Valley Regional         Eau Claire    WI     USA   
217  DBQ                  Dubuque Municipal            Dubuque    IA     USA   
218  RST            Rochester International          Rochester    MN     USA   
219  UTM           Tunica Municipal Airport             Tunica    MS     USA   
220  BIL                Billings Logan Intl           Billings    MT     USA   

           lat        long    cnt  
0    41.979595  -87.904464  25129  
1    33.640444  -84.426944  21925  
2    32.895951  -97.037200  20662  
3    33.434167 -112.008056  17290  
4    39.858408 -104.667002  13781  
..         ...         ...    ...  
216  44.865257  -91.485072     48  
217  42.402959  -90.709167     48  
218  43.908826  -92.497987     37  
219  34.681499  -90.348816     32  
220  45.807662 -108.542861     23  

[221 rows x 8 columns]

In [16]:
# 1 Print rows where Count > 10,000

subset10k = a_df[a_df.cnt > 10000]
rows10k = subset10k.shape[0] # number of rows
print(f"{rows10k} airports have air traffic greater than 10,000.")

10 airports have air traffic greater than 10,000.


In [17]:
# 2 Print all Column Names

print(list(a_df.columns.values))

['iata', 'airport', 'city', 'state', 'country', 'lat', 'long', 'cnt']


In [43]:
# 3 Print the 10th and 3rd rows of the dataset

a_df.loc[[10,3]]

iata                           airport            city state country  \
10  SLC               Salt Lake City Intl  Salt Lake City    UT     USA   
3   PHX  Phoenix Sky Harbor International         Phoenix    AZ     USA   

          lat        long    cnt  
10  40.788388 -111.977773   9898  
3   33.434167 -112.008056  17290

In [19]:
# 4 Which state had the 8th most traffic

statecnt = a_df.groupby('state')['cnt'].sum().reset_index()

statesort = statecnt.sort_values('cnt', ascending = False)


trafficmost8 = statesort['cnt'].iloc[7]
statemost8 = statesort['state'].iloc[7]
trafficmost8f = (f"{trafficmost8:,}")

print(f"{statemost8} was the state with the 8th most traffic with {trafficmost8f} flights.")

CO was the state with the 8th most traffic with 17,005 flights.


In [25]:
# 5 Which state had the 2nd most number of airports

stateairports = pd.DataFrame(a_df['state'].value_counts()).reset_index()
stateairports2 = stateairports['index'].iloc[1]
stateairportscnt = stateairports['state'].iloc[1]

print(f"{stateairports2} was the state with the 2nd most airports with {stateairportscnt} airports.")

TX was the state with the 2nd most airports with 17 airports.


In [87]:
# 6 Of the cities that have multiple airports, which one has the least total traffic for all airports?
#create abbr by city
#aggregate total traffic & how many different airports there are
#aggreagte airport(distinct) and count(sum)
#groupbind & agg


In [117]:
# 6 Of the cities that have multiple airports, which one has the least total traffic for all airports?

amod = a_df
amod["city-state"] = a_df['city'].astype(str) +"-"+ a_df["state"]
amod['Freq'] = amod.groupby('city-state')['city-state'].transform('count')
amod1 = amod[amod["Freq"] > 1]

citycnt = amod1.groupby('city')['cnt'].sum().reset_index().sort_values(by=['cnt'], ascending = True)

cityleast = citycnt['city'].iloc[0]
trafficleast = citycnt['cnt'].iloc[0]
trafficleastf = (f"{trafficleast:,}")

print(f"Of the cities with multiple airports, {cityleast} has the least total traffic with {trafficleastf} flights.")

Of the cities with multiple airports, New York has the least total traffic with 13,337 flights.


In [40]:
# 7 What is the total airport traffic for all states that border the state of Massachusetts?

maborderdb = statecnt[statecnt['state'].isin(['VT','NH','CT','NY','RI'])]
mabordertraffic = maborderdb['cnt'].sum()
mabordertrafficf = (f"{mabordertraffic:,}")

print(f"All of the states that border MA had {mabordertrafficf} total flights.")

All of the states that border MA had 22,007 total flights.


# Sources
https://stackoverflow.com/questions/5469286/how-to-get-the-index-of-a-maximum-element-in-a-numpy-array-along-one-axis#:~:text=There%20is%20argmin()%20and,of%20a%20numpy%20array%20respectively.&text=Note%20that%20these%20will%20only%20return%20the%20index%20of%20the%20first%20occurrence

https://www.tutorialspoint.com/numpy/numpy_dot.htm

https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://www.geeksforgeeks.org/how-to-get-column-names-in-pandas-dataframe/

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

https://stackoverflow.com/questions/16729574/how-can-i-get-a-value-from-a-cell-of-a-dataframe

https://stackoverflow.com/questions/1823058/how-to-print-a-number-using-commas-as-thousands-separators

https://www.statology.org/pandas-add-count-column/

https://sparkbyexamples.com/pandas/pandas-combine-two-columns-of-text-in-dataframe/

https://stackoverflow.com/questions/37787698/how-to-sort-pandas-dataframe-from-one-column